I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 233, in script
    python:
  File "game/script.rpy", line 235, in <module>
    winner = ui.interact(suppress_overlay=True, suppress_underlay=True)
AttributeError: 'tuple' object has no attribute 'visit_all'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 233, in script
    python:
  File "C:\Program Files (x86)\RenPy\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files (x86)\RenPy\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 235, in <module>
    winner = ui.interact(suppress_overlay=True, suppress_underlay=True)
  File "C:\Program Files (x86)\RenPy\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 2793, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 495, in visit_all
    d.visit_all(callback)
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 495, in visit_all
    d.visit_all(callback)
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 495, in visit_all
    d.visit_all(callback)
  File "C:\Program Files (x86)\RenPy\renpy\display\core.py", line 495, in visit_all
    d.visit_all(callback)
AttributeError: 'tuple' object has no attribute 'visit_all'

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Go Go Bernie Sanders! 1.26
